version: 2
jobs:
  build:
    working_directory: ~/dresden
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install package dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: pwd; ls
      - run:
          name: Running Black on source code
          command: |
            . venv/bin/activate
            black dresden
      - run:
          name: Running Flake8 on source code
          command: |
            . venv/bin/activate
            flake8 dresden
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv