version: 2
jobs:
  build_3.6:
    working_directory: ~/dresden
    docker:
      - image: circleci/python:3.6
    steps: &steps
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install package dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Installing graphviz
          command: sudo apt-get install graphviz
      - run:
          name: Running Black on source code
          command: |
            . venv/bin/activate
            black dresden
      - run:
          name: Running Flake8 on source code
          command: |
            . venv/bin/activate
            flake8 dresden
      - run:
          name: Running isort on source code
          command: |
            . venv/bin/activate
            isort .
      - run:
          name: Running unit tests
          command: |
            . venv/bin/activate
            pytest
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv

  build_3.7:
    docker:
      - image: circleci/python:3.7
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build_3.6
      - build_3.7